### ISSUE TITLE
sd2snes: FIFA 97 PAL-to-NTSC Patched (Europe) (En,Fr,De,Es,It,Sv) v2 GhostlyDark

### ISSUE THREAD

**Issue by tjanas** [frederic-mahe/Hardware-Target-Game-Database#162]
The [IPS patch](https://evilgames.eu/emulation.htm#snes-ntsc-patches) for `FIFA - Road to World Cup 98 (Europe) (En,Fr,De,Es,It,Sv).sfc` does not make any changes to the ROM. The SMDB reflects this with a checksum identical to the source ROM. Should this patched ROM be removed from the SMDB in the meantime?

**Comment by frederic-mahe** [comment]
Yes, I think it should be removed.
