### ISSUE TITLE
MiSTer.txt: Duplicates found with different names

### ISSUE THREAD

**Issue by dukrous** [frederic-mahe/Hardware-Target-Game-Database#259]
Was digging through the MiSTer.txt today and found a lot of duplicate files with different names and in different folders. Also, should the Atari2600 folder have a duplicate of Atari 2600 SMDB.txt? Just posing that question.

Attached is a text file with the duplicate lines.

[MiSTer Duplicates.txt](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/files/4568523/MiSTer.Duplicates.txt)

**Comment by frederic-mahe** [comment]
Thanks @dukrous 

Many of these duplicates were fixed in their respective SMDBs. The fastest solution would be to rebuild and parse a new MiSTer SMDB using the latest Atari 2600 pack.
