### ISSUE TITLE
Atari Lynx - possible typo

### ISSUE THREAD

**Issue by Infinitum8t** [frederic-mahe/Hardware-Target-Game-Database#530]
This filename has an improper extension. Looks like a typo.

Yastuna Volume 2 - The Space (PD) Fadest 2008.textClipping

**Comment by tjanas** [comment]
@Infinitum8t i agree, it looks like this was added with this commit: https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/0356d29066b959d899523fcf65b259c99873fdb6#r46525219

**Comment by tjanas** [comment]
@tjstogy can you take a look

**Comment by tjanas** [comment]
Resolved via https://github.com/frederic-mahe/Hardware-Target-Game-Database/pull/562
