### ISSUE TITLE
Sega Saturn Supplement - Vandal Hearts English - Ushinawareta Kodai Bunmei (J) T+Eng v1.4  .CUE issue

### ISSUE THREAD

**Issue by NJL82** [frederic-mahe/Hardware-Target-Game-Database#546]
The .cue file no longer matches. There seems to have been 2 updates, named 1.4, to the patch and this may have caused the inconsistency

**Comment by tjanas** [comment]
@NJL82 can you provide more details on this issue?

```
6bae252e67460fa7b616adb6d5da9c3a4a92589fa35742a8874b6628f02c2f07	Saturn Redump Supplement/Vandal Hearts English - Ushinawareta Kodai Bunmei (J) T+Eng v1.4 paul_met, Stardust Crusaders/Vandal Hearts - Ushinawareta Kodai Bunmei (Japan) [T+En v1.4 by paul_met, Stardust Crusaders] (Track 1).bin	61509993c9d7d14d5a646ca0e8c4805931c1773b	119260a2e84b8f022405e66894289085	4229c707
245f3f846b483bb2028f2ce86277b4fea5c98f2f5412450f97b6e3b198ac4915	Saturn Redump Supplement/Vandal Hearts English - Ushinawareta Kodai Bunmei (J) T+Eng v1.4 paul_met, Stardust Crusaders/Vandal Hearts - Ushinawareta Kodai Bunmei (Japan) [T+En v1.4 by paul_met, Stardust Crusaders] (Track 2).bin	14650f667b9f9cfcd667bcfce677520c050c4a99	bc7753a86795d8829eab932aea8750e7	7867bb24
a5da7348ad2962b3d016ca04b1171af4294478412c12b207f723ca8da3d1fe56	Saturn Redump Supplement/Vandal Hearts English - Ushinawareta Kodai Bunmei (J) T+Eng v1.4 paul_met, Stardust Crusaders/Vandal Hearts - Ushinawareta Kodai Bunmei (Japan) [T+En v1.4 by paul_met, Stardust Crusaders].cue	309acf7791bc86d604f1797c2b9d4f5fbb689f70	0f7803a0c67d62e7f508ba833ba26fd6	b177d456
```

cue file contents:
```
CATALOG 0000000000000
FILE "Vandal Hearts - Ushinawareta Kodai Bunmei (Japan) [T+En v1.4 by paul_met, Stardust Crusaders] (Track 1).bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
FILE "Vandal Hearts - Ushinawareta Kodai Bunmei (Japan) [T+En v1.4 by paul_met, Stardust Crusaders] (Track 2).bin" BINARY
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
```

**Comment by NJL82** [comment]
The cue file I am left with after the patch is 

7e9f52bbecc67cb9597d863101036cecee02862b1229855bc5ca3f02354bafa3	Saturn Redump Supplement/Vandal Hearts - Ushinawareta Kodai Bunmei (Japan)/Vandal Hearts - Ushinawareta Kodai Bunmei (Japan).cue	8a81938a0da2108807a5ecf21e641ff681bac671	a5f37a299f87eb4adecd53d6c558a800	06337bc4

On Romhacking, there are 2 references for patch 1.4. I'm wondering if the patch was updated after the log was taken and thus the inconsistency in the cue numbers. The 2 bin files match but the CUE is not. Thanks

Patch history:

Initial release [v1.1];
Improved compatibility with 4 MB Extended RAM Cartridge [v1.2];
Support for official 4 MB Extended RAM Cartridge [v1.3];
Added the ability to skip cinematics (by clicking START) [v1.4];
Added a HARD MODE (activated by pressing the L+R buttons on the title screen of the game after each restart) [v1.4];

**Comment by tjanas** [comment]
If your bin files match, use the cue file contents I provided above and you should be good to go.

**Comment by NJL82** [comment]
I'm using the patch from RHDN and the confirmed REDUMP version of the rom to use by RHDN and redump.org  (MD5, SHA-1 and CRC-32 numbers match). I run the patch and the .BIN file numbers match those expected. However, those for the .CUE do not and give the following.

SHA-256 Checksum: 7E9F52BBECC67CB9597D863101036CECEE02862B1229855BC5CA3F02354BAFA3
MD5 Checksum: A5F37A299F87EB4ADECD53D6C558A800
SHA-1 Checksum: 8A81938A0DA2108807A5ECF21E641FF681BAC671

After I alter the .CUE file, with the information you gave above, they change to this.

SHA-256 Checksum: 4510B600EED8B011F2A4CB02B2D874ACC40C9F1830F73386B0F20703A1BE7725
MD5 Checksum: 4B39C8EF9E99354A88D90BFA4F5391D1
SHA-1 Checksum: FAE1B724D78B16600BDB6ADCE74716280F1194AD

I'm not sure if there is a reason for this, or I'm doing something wrong, but the patch process completes successfully. It seems that the MD5 & SHA-1 numbers are the same before and after patching too and do not change.

Thanks for all the help!

**Comment by NJL82** [comment]
> If your bin files match, use the cue file contents I provided above and you should be good to go.

I'm using the patch from RHDN and the confirmed REDUMP version of the rom to use by RHDN and redump.org (MD5, SHA-1 and CRC-32 numbers match). I run the patch and the .BIN file numbers match those expected. However, those for the .CUE do not and give the following.

SHA-256 Checksum: 7E9F52BBECC67CB9597D863101036CECEE02862B1229855BC5CA3F02354BAFA3
MD5 Checksum: A5F37A299F87EB4ADECD53D6C558A800
SHA-1 Checksum: 8A81938A0DA2108807A5ECF21E641FF681BAC671

After I alter the .CUE file, with the information you gave above, they change to this.

SHA-256 Checksum: 4510B600EED8B011F2A4CB02B2D874ACC40C9F1830F73386B0F20703A1BE7725
MD5 Checksum: 4B39C8EF9E99354A88D90BFA4F5391D1
SHA-1 Checksum: FAE1B724D78B16600BDB6ADCE74716280F1194AD

I'm not sure if there is a reason for this, or I'm doing something wrong, but the patch process completes successfully. It seems that the MD5 & SHA-1 numbers are the same before and after patching too and do not change.

Thanks for all the help!
