### ISSUE TITLE
Atari Lynx: Improper filename ext for Yastuna Volume 2

### ISSUE THREAD

**Issue by birdybro** [frederic-mahe/Hardware-Target-Game-Database#560]
https://github.com/frederic-mahe/Hardware-Target-Game-Database/blob/33877463a5712ddbcbd7b8f0d2a421bf5ad235c1/EverDrive%20Pack%20SMDBs/Atari%20Lynx%20SMDB.txt#L255

https://github.com/frederic-mahe/Hardware-Target-Game-Database/blob/33877463a5712ddbcbd7b8f0d2a421bf5ad235c1/EverDrive%20Pack%20SMDBs/Atari%20Lynx%20SMDB.txt#L502

Both instances of Yastuna Volume 2 appear to have an improper filename extension in the db.

Side note: I downloaded from 4 different official-ish sources to try and find the rom that matches this hash, and it still comes up missing when I run the build. It's the last one :P. Something's probably up with this entry beyond just the filename extension.

Below is a screenshot showing the 4 versions I have all of which do not match the entry in the db.

![image](https://user-images.githubusercontent.com/16388068/111214153-37f08e80-8597-11eb-94aa-1c88e3c75090.png)

**Comment by tjanas** [comment]
@tjstogy can you please take a look?

**Comment by frederic-mahe** [comment]
Good timing! An Atari Lynx core for the MiSTer should be released anytime soon.

**Comment by birdybro** [comment]
I've been trying it out a bunch. I wanted to try the everdrive pack on it since the headers might be wrong on these as compared to the pack that is officially supported by the core's dev at the moment.

**Comment by tjanas** [comment]
I believe this is now resolved per https://github.com/frederic-mahe/Hardware-Target-Game-Database/pull/562
