### ISSUE TITLE
FDS: Tanigawa Kouji...Tsugi no Itte (Japan) (Disk Writer) [Merged].fds 

### ISSUE THREAD

**Issue by Infinitum8t** [frederic-mahe/Hardware-Target-Game-Database#574]
As per instructions of #437: 
side A from "Tanigawa Kouji no Shougi Shinan II - Meijin e no Michi (Japan).fds" is merged with "Tanigawa Kouji no Shougi Shinan II - Meijin e no Michi - Shinban Tsumeshougi - Tsugi no Itte (Japan) (Disk Writer).fds". 
The SMDB result is 2aded20b.

The following source files were found and used to merge in various combinations with no luck:
Tanigawa Kouji no Shougi Shinan II - Meijin e no Michi (Japan).fds (131,000 bytes)
6cad684c
32d8f70f
Tanigawa Kouji no ShoTanigawa Kouji no Shougi Shinan II - Meijin e no Michi - Shinban Tsumeshougi - Tsugi no Itte (Japan) (Disk Writer).fds (65,500 bytes)
14983091
94ed2d89

Merging was also attempted with files containing headers and still no luck. Could someone shed more light on this please?

**Comment by tjanas** [comment]
Did you take the leading 65500 bytes (first half of the file) from "Tanigawa Kouji no Shougi Shinan II - Meijin e no Michi (Japan).fds", followed by appending “ Tanigawa Kouji no ShoTanigawa Kouji no Shougi Shinan II - Meijin e no Michi - Shinban Tsumeshougi - Tsugi no Itte (Japan) (Disk Writer).fds”? The total new file size is 131000 bytes.

**Comment by Infinitum8t** [comment]
I did. I even went a little further. The files are represented as 6cad684c=1, 32d8f70f=2, 14983091=5, 94ed2d89=6.

They were then combined and these were the results:
1 + 5 = 6e3c14ca
1 + 6 = ee4909d2
2 + 5 = 95042aad
2 + 6 = 157137b5
5 + 1 = 38434B0e
5 + 2 = 6636d44d
6 + 1 = 6aa333de
6 + 2 = 34d6ac9d

**Comment by Infinitum8t** [comment]
> Did you take the leading 65500 bytes (first half of the file) from "Tanigawa Kouji no Shougi Shinan II - Meijin e no Michi (Japan).fds", followed by appending “ Tanigawa Kouji no ShoTanigawa Kouji no Shougi Shinan II - Meijin e no Michi - Shinban Tsumeshougi - Tsugi no Itte (Japan) (Disk Writer).fds”? The total new file size is 131000 bytes.

Wait a sec!
One file is 65500 bytes and the second file is 131000 bytes. Both merged should equal 195,500 bytes, no?

**Comment by tjanas** [comment]
No. You have to take half of the first file (just its side A, not both of its sides). So just the leading 65500/131000 bytes of file1, plus the whole 65500 bytes of file 2.

**Comment by tjanas** [comment]
Each FDS disk side is 65500 bytes. The end result should be side A from file1, plus all of file2 (file2 is a single-sided disk file that represents a replacement side B).

**Comment by Infinitum8t** [comment]
Ugh. The moment I looked closer at each FDS disk side, I realized my error. 

For anyone else attempting this, remove the second half of 6cad684c. The result is a9257858. Merge that with 94ed2d89 and you'll get (drumroll...) 2aded20b.

Feel free to close this issue.
