### ISSUE TITLE
5200:  Bounty Bob Strikes Back (Unl).atr

### ISSUE THREAD

**Issue by Infinitum8t** [frederic-mahe/Hardware-Target-Game-Database#578]
edae6bef1f86c05405b6f236e8ce335e94a0849bb5207f9d0046069a99c45b20
Atari 5200/4 Hacks & Homebrew/Bounty Bob Strikes Back (Unl).atr	
2736c358409c06a60af5ccc27fef1bd99fc1c340	1d1dcd2fc898e8680eec362c74b29e5f	11e783fd

Regarding the entry listed above in the SMDB, it wasn't in the old "Atari 5200 - Atarimax v1.0.7z" release, or no-intros either. Haven't been able to locate this one anywhere. Is this unlicensed, unreleased, and old Homebrew version, something else? Is it still in the wild?

**Comment by tjanas** [comment]
Looks like it got added with this commit: https://github.com/frederic-mahe/Hardware-Target-Game-Database/commit/8a56116cddf9311fb5f7c7016618f680a683047e#diff-6d09ea648638af27f530aa7c6813f0e40482397cc4391f9d36fcf3bbdb5d5a74

**Comment by Infinitum8t** [comment]
Yep. I saw that. 50 additions were made and 47 deletions. 
Later that day 2 more deletions were made.

Is there another clue?! :)

**Comment by tjanas** [comment]
My vote is to remove it for now.

**Comment by Infinitum8t** [comment]
The completionist would say no.
Myself, and a few other have been searching for that file for a few months now. No luck.
Already have the USA full release. Not sure what that version has to offer.

I vote to remove it as well so I can lay my OCD on this matter to rest.
