### ISSUE TITLE
MegaSD: Marko mismatch and Timecop (unreleased beta)

### ISSUE THREAD

**Issue by Infinitum8t** [frederic-mahe/Hardware-Target-Game-Database#580]
Regarding the entry "Marko (USA) (Unl) (Track 01).bin", the SMDB shows the file as d6815343. Various searches, including extraction from CHD file shows the checksum as 973e0724 and 16,174,704 bytes.

The files:
Timecop (2007)(Good Deal Games)(NTSC)(US)(Track 1 of 2)[!][unreleased beta].iso
Timecop (2007)(Good Deal Games)(NTSC)(US)(Track 2 of 2)[!][unreleased beta].wav
Timecop (2007)(Good Deal Games)(NTSC)(US)[!][unreleased beta].cue

appear elusive. Faint rumours discussed they MIGHT be hidden in an old CHD MAME file several years old. Not much luck tracking it down.

**Comment by tjanas** [comment]
I believe the Marko checksum is referenced here: http://redump.org/disc/61255/

**Comment by tjanas** [comment]
It appears there are two different pressings of Marko; this is the other one which matches the other checksum you provided: http://redump.org/disc/73145/

**Comment by tjanas** [comment]
`Timecop (Europe) (Beta) (1995-03-14)` should be removed from this database since it references an MP3 track that is not going to work on any real hardware.
