### ISSUE TITLE
MiSTer Neo Geo - unable to find the correct file

### ISSUE THREAD

**Issue by sanselon** [frederic-mahe/Hardware-Target-Game-Database#589]
Hello,

I am unable to find a specific file. It being a Zip makes thing even harder, as different compression settings output different possibilities. Is there a way to solve this problem or use files that are not compressed?

The file in question:
Metal Slug 6 (mslug3b6).zip	ff22e5130a6576ada898b8cf37c1d7788c37cdea1252f83dae2a7395433a4e25

Thank you for your help.

**Comment by frederic-mahe** [comment]
hello @sanselon 

The file you are looking for is the same as this one:
```
6fa190e97a1228c34365a02ee3b0455dba91124e2251ab29bb42bbe6f6a13d81	MiSTer Add On Packs/Games/NEOGEO/2 Unlicensed - A-Z/Metal Slug 6 (Metal Slug 3 boot) (mslug3b6).neo	0b7668056de35edcf375e8b155041c50b01da94c	1d5988c4ef310a6cbf5dab6d5269beca	f70d50cb
```
If you don't already have it, the hash values should help you find an exact copy.

**Comment by tjanas** [comment]
Fixed in https://github.com/frederic-mahe/Hardware-Target-Game-Database/commit/dc05956b98dbd147c50adb8b6e0fabcf12b88206
