### ISSUE TITLE
parse_pack.py: make banned_suffixes case-insensitive

### ISSUE THREAD

**Issue by tjanas** [frederic-mahe/Hardware-Target-Game-Database#592]
Make the following check case-insensitive, so that both `.txt` and `.TXT` (or mixed-case permutations) files will be ignored by the parse_script.
```
if not (any(s in filename for s in banned_folders) or
        filename.endswith(banned_suffixes)):
```

**Comment by frederic-mahe** [comment]
fixed in dc03638bf8aec177c5017906bc360f05357679ac
