### ISSUE TITLE
Mega EverDrive SMDB Has Possible Overdump in Game Series Collection (and other possible issues)

### ISSUE THREAD

**Issue by RastaJedi** [frederic-mahe/Hardware-Target-Game-Database#597]
Hi,

The game '**Flashback - The Quest for Identity (USA)**' with SHA-1 sum _bce40031f6adab48670c8a2d73e42f3a3dcba97c_ is only referenced under 'Top 100 List - Retro-Sanctuary.com' and 'V's Recommended Games - 4chan'. The actual ROM in the main US folder has SHA-1 sum _1a44eb9606088692b8559852e8f7b7c1a1472b6e_, and is titled '**Flashback - The Quest for Identity (USA) (En,Fr)**'. I spent quite a while trying to figure out what the former was, and I've found two results. Romhacking.net has this under English to Spanish translation: https://www.romhacking.net/translations/3677/. But, I also found this: https://github.com/redscientistlabs/RTC-0.7-Deprecated-/blob/master/Output%20RTC/BizHawk/gamedb/gamedb_sega_md.txt, and if the DB on GitHub is to be believed, this is an overdump. I'm not sure if it's actually an overdump, or if it's simply a Spanish translation, but there's already a Spanish translation (_SHA-1: 9c35d211cfb7ec2a66c283e6a44d7369fbbeb2ca_), so I'm fairly confused as to what this is. Whether it's an overdump or not, if it should be kept in the SMDB, should it not go in a non-Game Series Collection folder, to specify what it is? Or should it be removed, and the ROM from the USA folder be placed in the Game Series Collection in its place?

Also, 'Gain Ground (Europe)' is only listed in Game Series Collection as well (_SHA-1: 148d166d594535c6526cb450c461cfb003b59f93_). I would think it should also be in the main Europe ROM folder? I'm not sure if this either of these are actually an issue or not. If they are not issues, feel free to close this!

'**Zhang Mahjong (Taiwan) (unl)**' is only in Game Series Collection too. I would think it should also be in the _Unlicensed_ folder?

'**After Burner II (UE) [T+Bra]**' is only in Game Series collection, and I think it should also be in _Translations_?

If any of these actually _should_ be in the spots I mention, I'd be willing to update the SMDB if I had access to.

Only one '(Genesis Mini)' ROM (a Mega Man one) is also in the main folder. So I'm not sure if the rest of them should be too, or if the Mega Man one shouldn't. They have different checksums than the originals; otherwise I wouldn't even have worried about them.

'**Altered Beast (W) (REV02) [T+Bra_OdinGames]**' (_c05ebee5d9fc20c21c0c4177854c807e4d398009_) and '**Altered Beast (W) (REV02) [T+Bra_Son_Car]**' (_77b50155f11c95b66e1b05a7499294054961375b_) are only in GSC (Game Series Collection).

I feel like I may just have a big misconception about this. I would have thought ROMs in the GSC should also be in the main folders somewhere too. But, there are so many, I'm starting to think I was wrong. I'm trying to create my own ROM set on my storage, and I'm trying to remove any dupes. Then, when I need to actually build an EverDrive pack, I just use hardlinks. So I was trying to organize them and remove redundant entries, but these have been issues I've ran into so far. Please, let me know if I have this mistaken. I would have thought the entire GSC would contain only hardlink/dupes, and I think that makes more sense, in case someone doesn't care about the categorization about the GSCs, but perhaps they are necessary to some extent...

It seems like the Genesis Mini and the ;Misc/Brazil Releases; parts of the GSC are necessary at least (besides that Mega Man game), but I'm not sure if this is on purpose.

There are also some '(Virtual Console)' ROMs only in the GSC.

'**Space Turtleship (Japan)**' (_SHA-1: 0eccbac0235307bbd62156a37742784b7745b82b_) is only in the GSC (any '_Space Turtleship_', for that matter).

**Comment by RastaJedi** [comment]
Also, '**Gain Ground (Europe)**' is only listed in Game Series Collection as well (SHA-1: _250033f6c91fbb7714782cd66fcece82_). I would think it should also be in the main Europe ROM folder? I'm not sure if this either of these are actually an issue or not. If they are not issues, feel free to close this!

**Comment by tjanas** [comment]
Your understanding is correct; a perfect pack should never have entries only within GSC (GSC should always be a subset of the other directories).

Honestly, I don’t trust most of those non-English translations and feel like they should be removed. I don’t think they have been vetted and were haphazardly added at some point long ago.

**Comment by RastaJedi** [comment]
Well, I'm glad I'm not crazy and didn't bother typing all of this up for nothing :). If they should be removed, that's cool, and I probably agree, but they should be removed entirely. If not, then they should be added into the mainstream set. Who do I have to talk to in order to be able to help collaborate in this repo? :) I'd be happy to help, where I can.

**Comment by tjanas** [comment]
The copy of Flashback in the main directory that you referenced is good. That file in GSC is bad. No-intro: https://datomatic.no-intro.org/index.php?page=show_record&s=32&n=0504

`bce40031f6adab48670c8a2d73e42f3a3dcba97c` is a confirmed bad dump in the link above (underdump)

**Comment by RastaJedi** [comment]
Oh, nice! I didn't even think to check the actual no-intro site. That would have made my research much easier :).

**Comment by tjanas** [comment]
> Well, I'm glad I'm not crazy and didn't bother typing all of this up for nothing :). If they should be removed, that's cool, and I probably agree, but they should be removed entirely. If not, then they should be added into the mainstream set. Who do I have to talk to in order to be able to help collaborate in this repo? :) I'd be happy to help, where I can.

I’d be happy to collaborate with you. Thank you for being a fellow detail-oriented user and bringing attention to these legitimate issues.

**Comment by tjanas** [comment]
> Oh, nice! I didn't even think to check the actual no-intro site. That would have made my research much easier :).
> Should I keep posting discrepancies I find here? Or can I clone and do a pull request or something?

Either one is fine. If you do a pull request, try to make changes that aren’t too massive to make a diff review difficult.

**Comment by RastaJedi** [comment]
Alright, cool! Thank you! I'm pretty brand new to the SMDB project, but I'm already a huge fan... and I'm sort of OCD about these things haha. I'd be honored to be able to help perfect it/clean it up!

**Comment by RastaJedi** [comment]
This will be my first attempt at ever submitting a pull request... I'll fork the repo, make a couple of the aforementioned changes, and submit a pull request. Please let me know if I did it correctly afterwards :).

**Comment by tjanas** [comment]
> This will be my first attempt at ever submitting a pull request... I'll fork the repo, make a couple of the aforementioned changes, and submit a pull request. Please let me know if I did it correctly afterwards :).
> 
> Edit: I only made one change, to ensure I did this correctly. Please let me know if I did it right? @tjanas

Perfect. Your pull request has been merged.

**Comment by RastaJedi** [comment]
Thanks! I'll keep cracking away at it when I have free time!
