### ISSUE TITLE
SNES: eliminate Special Chip Games directory 

### ISSUE THREAD

**Issue by tjanas** [frederic-mahe/Hardware-Target-Game-Database#612]
This directory contains official “special chip” releases from no-intro, SA-1 conversions, SA-1 conversion hacks, and hacks of official SA-1 games, plus translations and hacks of other official special chip releases. I believe it would be cleaner for only one copy to exist in the pack (besides GSC), and that translations and hacks should be in those respective directories exclusively.

If games should still be grouped by their chip type, I feel that could be achieved via Game Series Collections.

Thoughts?

**Comment by tjstogy** [comment]
I like your idea. Also, perhaps in Hacks, it can remain in a Special Chips directory instead of just mixed in.

**Comment by frederic-mahe** [comment]
> If games should still be grouped by their chip type, I feel that could be achieved via Game Series Collections.

Agreed.

Regarding SA-1 hacks and SA-1 conversion hacks, I think they should be placed among other hacks. Maybe collections of SA-1 conversions and SA-1 hacks could be transferred to the GSC?

**Comment by RastaJedi** [comment]
I for sure agree, only categorized by chip type in GSC.

**Comment by tjanas** [comment]
Pull request created to eliminate this subdirectory. It does not recreate a Special Chips subdirectory equivalent in GSC. That could be done at a later time if desired.
