### ISSUE TITLE
Saturn: Sega Rally Championship Plus patch info

### ISSUE THREAD

**Issue by tjanas** [frederic-mahe/Hardware-Target-Game-Database#613]
Does anyone know how to obtain the patch for `Sega Rally Championship Plus - Widescreen (J) v1 paul_met` in the Saturn supplement?

**Comment by NJL82** [comment]
You need to use a hex editor to edit a specific file in the first bin file as posted here [Sega Rally Championship Plus Widescreen Info](https://segaxtreme.net/threads/screeen-resolution-hacks.24034/post-177694)

**Comment by tjanas** [comment]
@NJL82 can you help break down the specific bytes that need to be changed and to what values? I saw that page but the instructions did not seem obvious to me,

**Comment by tjanas** [comment]
Thank you!! Those steps worked perfectly and results in a match.
