### ISSUE TITLE
SNES: rename Tecmo Secret of the Stars (U) T+Ger v0.98 Alemaniac Translation

### ISSUE THREAD

**Issue by tjanas** [frederic-mahe/Hardware-Target-Game-Database#618]
[This translation](https://snes-projects.de/filebase/index.php?file/123-secret-of-the-stars-t-ger0-98-alemanic-translations/) is listed by the author as beta and incomplete; the filename should indicate this via "T-Eng" instead of "T+Eng"

**Comment by himanshu007-creator** [comment]
I would like to work on this issue. Please can you specify the folder that needs to be modified.
Plus share the instructions

**Comment by tjanas** [comment]
@himanshu007-creator This is the filename in question:
`SD2SNES/4 Translations/Non-English/German/Tecmo Secret of the Stars (U) T+Ger v0.98 Alemaniac Translation.sfc`

**Comment by tjanas** [comment]
@himanshu007-creator are you going to fix?

**Comment by himanshu007-creator** [comment]
i want to do this, but can  guide what exactly needs to be done?

**Comment by tjanas** [comment]
Change
`Tecmo Secret of the Stars (U) T+Ger v0.98 Alemaniac Translation.sfc`
to
`Tecmo Secret of the Stars (U) T-Ger v0.98 Alemaniac Translation.sfc`
in [Super EverDrive & SD2SNES SMDB.txt](https://github.com/frederic-mahe/Hardware-Target-Game-Database/blob/master/EverDrive%20Pack%20SMDBs/Super%20EverDrive%20%26%20SD2SNES%20SMDB.txt)
