### ISSUE TITLE
MiSTer (NES): add Kid Dracula sav file

### ISSUE THREAD

**Issue by tjanas** [frederic-mahe/Hardware-Target-Game-Database#645]
`Kid Dracula (USA, Europe) (Castlevania Anniversary Collection).nes` requires and uses a predefined save file as an extra ROM bank. This save file is part of the [no-intro dat](https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=2846). It needs to be included (like it is for the Nt Mini packs).

The following should be added:
```
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855	MiSTer/saves/NES/@Kid Dracula save file is used as an extra ROM bank by the game	da39a3ee5e6b4b0d3255bfef95601890afd80709	d41d8cd98f00b204e9800998ecf8427e	00000000
e4fd5424036d6b4de9683034662129fb49f17812cb49f4dddd5ac6db6573b7c3	MiSTer/saves/NES/Kid Dracula (USA, Europe) (Castlevania Anniversary Collection).sav	1004aec3f6ff9d2135c0a5150e37aa8250f4f22b	dce27edb434d238613f928daa5c50632	aba5001b
```

**Comment by LodanZark** [comment]
There is a fixed version that does not require the sav file:

`<game>

<prgrom size="262144" crc32="CDC2B349" sha1="8FB2916F35372149E5EF44ACB0866D427A13B20A" sum16="031D"/>
<chrrom size="131072" crc32="2BC4EF48" sha1="5E8DBA26D71CE3DAA06BD99E953A42E89A1A3745" sum16="1773"/>
<rom size="393216" crc32="166C2418" sha1="FE44C70204FCE9217F194C4010CC2130A82E08A2"/>
<prgram size="8192"/>
<pcb mapper="23" submapper="2" mirroring="H" battery="0"/>
<console type="0" region="0"/>
<expansion type="1"/>
</game>`

iNES header: `4E 45 53 1A 10 10 70 18 20 00 07 00 00 00 00 01`

The file can be found in the finalburn neo or the NewRisingSun ines2.0 romset

**Comment by tjanas** [comment]
Yes, but for completeness the sav file should be included like any other ROM, especially since the sav file is part of the no-intro NES set.

**Comment by LodanZark** [comment]
Correct, .sav file is being used as an additional ROM bank and contains data necessary for the game to run properly.
