### ISSUE TITLE
HTGDB script for MiSTer

### ISSUE THREAD

**Issue by thehughhefner** [frederic-mahe/Hardware-Target-Game-Database#671]
Hi,
Would it be possible to run the different scripts in the MiSTer hardware? For example, if I have a complete set of sega Megadrive ROMs and I have them in a hard drive connected to mister. It would be nice to have a script to sort these in folders.

**Comment by tjanas** [comment]
That’s a question / issue better suited for https://github.com/MiSTer-devel/Scripts_MiSTer
