### ISSUE TITLE
parse_pack: filenames ending with "os.pce" are being excluded

### ISSUE THREAD

**Issue by tjanas** [frederic-mahe/Hardware-Target-Game-Database#680]
The following are valid SMDB entries:

`Turbo EverDrive/4 Game Series Collections/Best-Of Lists/Top 100 List - Retro-Sanctuary.com/024 Photograph Boy - Gekisha Boy (J) T+Eng v2 Zatos.pce`

`Turbo EverDrive/4 Game Series Collections/Best-Of Lists/V's Recommended Games - 4chan/Blue Blink - Aoi Blink (J) T+Eng v0.99b Gaijin+Zatos.pce`

Since `/TBED/` is already in banned_folders, an easy fix might be removing "os.pce" from banned_suffixes

**Comment by tjanas** [comment]
Maybe have a banned_filenames list in addition to banned_suffixes, where banned_filenames would contain "os.pce", "Thumbs.db", "menu.bin", "desktop.ini", and those would be removed from banned_suffixes.

**Comment by frederic-mahe** [comment]
Done in https://github.com/frederic-mahe/Hardware-Target-Game-Database/commit/908fe9c0b72c8c72e661bfb4b6ef825f4d3566a4 thanks @tjanas
