### ISSUE TITLE
Building MegaSD and Finding hash issues [Question]

### ISSUE THREAD

**Issue by jadehawk** [frederic-mahe/Hardware-Target-Game-Database#710]
Hi. First of all, Thank you all for bringing this game packs back to life..

I downloaded the current (as of 03/14/2021) copy of all packs available on archive.org (htgdb-gamepacks). and attemped to rebuild "MegaSD SMDB.txt" using "@Genesis - MegaSD Mega EverDrive 2021-04-28.zip / @Genesis - MegaSD Mega EverDrive Game Series Collections 2021-04-28.zip / MegaCD folder content (this one is full of Bin's & Cue's)" as the source and at the end of the process it says its 5266/8141 (64.68%) complete.

Looking at the generated "missing.txt" I can see that I do have some (Not All) of the missing files inside the MegaCD folder, but the ones that I do have, do not match the hash..

Is this normal?
Why do the files d/l from Archive.org do not match the hash inside the MegaSD SMDB.txt?
Is there a way to ignore the hash check while building the pack?

TIA for any help

**Comment by tjanas** [comment]
There is no affiliation here with whatever random files you are finding on the internet.
