### ISSUE TITLE
NewRisingSun NES2.0 XML DB Update (2012-12-17)

### ISSUE THREAD

**Issue by LodanZark** [frederic-mahe/Hardware-Target-Game-Database#730]
The NewRisingSun NES2.0 XML db new update it's available: https://forums.nesdev.org/viewtopic.php?t=19940

**Comment by tjanas** [comment]
The NES2.0 XML DB is still in flux (currently 2021-12-25 is the latest update). Also, no-intro is thinking about creating a dat file for NES2.0-headered NES roms.

**Comment by LodanZark** [comment]
That's amazing news, that would help a lot to mitigate the bad headers floating around on the web!
