### ISSUE TITLE
Extra information at the end of the line

### ISSUE THREAD

**Issue by qjao** [frederic-mahe/Hardware-Target-Game-Database#740]
The last two submits ([736](https://github.com/frederic-mahe/Hardware-Target-Game-Database/pull/736) and [737](https://github.com/frederic-mahe/Hardware-Target-Game-Database/pull/737)) on Game Boy introduced a few characters at the end of their respective lines.

[Game Boy/4 Homebrew/Dangan GB (PD) v1.1 snorpung.gb](https://github.com/frederic-mahe/Hardware-Target-Game-Database/commit/9778e0f6561119b61c135bd63580fc3f6c448a1d) 262144
[Game Boy/5 Tools & Service Test Carts/144p Test Suite (PD) v0.22 Damian Yerrick.gb](https://github.com/frederic-mahe/Hardware-Target-Game-Database/commit/2f0566b66b974e8a91607a7b2492ac77ddaa0287) 32768

Those are the only two lines with that 6 column of information.

**Comment by tjanas** [comment]
That’s the size column that was introduced to the parse_pack script. It should be ok, but for consistency, I can update the file so that the rest of the entries have the size field.
