### ISSUE TITLE
[ MiSTer FPGA ] New MegaAGS 2022.03.03 Available

### ISSUE THREAD

**Issue by tmznix** [frederic-mahe/Hardware-Target-Game-Database#769]
Scripts are here:

https://github.com/Optiroc/AGSImager

Other helpful files are already at archive.org

Thank you for your work, cheers!

**Comment by tjanas** [comment]
Can you provide more details?

**Comment by tmznix** [comment]
The idea is to replace the old version of the MiSTer Amiga Add-On (from version 2021-03-13) with the new one (from 2022-03-03):

https://github.com/frederic-mahe/Hardware-Target-Game-Database/blob/ad159b459d0a1b4e24e1fd40badcc1eb0d68bc94/EverDrive%20Pack%20SMDBs/MiSTer%20Amiga%20Add-On.txt

What other details do you need? 

Thank you for answering! Cheers.

**Comment by tjanas** [comment]
Which entries in that SMDB file would change, how would they change, and what explicit steps to generate/obtain the checksums that are changed?

**Comment by tjanas** [comment]
A pull request with said changes and documentation describing how to reproduce the new checksums.

**Comment by tmznix** [comment]
Well, I never done that before, maybe with some guiding.... What checksums are needed? Are they needed in a specific order?
The details on how to reproduce the files are here:

https://github.com/Optiroc/AGSImager

:)
