### ISSUE TITLE
Game Boy Color SMDB.txt 

### ISSUE THREAD

**Issue by graschbaten** [frederic-mahe/Hardware-Target-Game-Database#795]
Hi, the Game Boy Color SMDB.txt Roms need to sort into the MiSTer GB or GB2P Folder

**Comment by tjanas** [comment]
Hello. Yes, you can place both GB and GBC into MiSTer’s Gameboy directory for games. And you can symlink both of those subdirectories/zip files into your Gameboy2P games directory.
