### ISSUE TITLE
Case Sensitive Issue within MiSTer MSX Add-On.txt

### ISSUE THREAD

**Issue by muggsyd** [frederic-mahe/Hardware-Target-Game-Database#824]
Currently the MiSTer.txt creates and  maintains a **C**onfig folder at the root.

The MiSTer MSX Add-On creates a **c**onfig folder. This should be changed to maintain the correct folder format across packs

**Comment by frederic-mahe** [comment]
@muggsyd do you mean that the case should be the same in both packs? either `config` or `Config` everywhere?

If yes, then which case should be preferred?

**Comment by muggsyd** [comment]
I just tested on my current MiSTer setup, and it creates a config folder (all lower case). So based on that I assume that lowercase is the correct format and that it is the MiSTer.txt file that is incorrect in relation to his bug report
