### ISSUE TITLE
Source of hashes?

### ISSUE THREAD

**Issue by yo1dog** [frederic-mahe/Hardware-Target-Game-Database#827]
Where do the hash values come from? They don't match no-intro.

For example, NES `Super Mario Bros. (World)` has CRC32 `393a432f` (headered) in no-intro but is `3337ec46` in `EverDrive N8 - PowerPak SMDB.txt`.

https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=2147

**Comment by tjanas** [comment]
EverDrive N8 most likely uses iNES 1.0 headers, whereas no-intro headered uses NES2.0 headers based on NewRisingSun xml. The EverDrive N8 smdb is generally deprecated in favor of the NES2.0 smdb.

**Comment by yo1dog** [comment]
Got it. I will switch to NES2.0 smdb.

I am still curious on what ROM set the hashes are pulled from for N8 smdb.

**Comment by tjanas** [comment]
If you convert to an iNES1.0 header, you should obtain the hash.

**Comment by yo1dog** [comment]
Interesting. I'll try that as there does not seem to be a Game Series Collections for NES2.0.

**Comment by tjanas** [comment]
Yeah, the GSC becomes very difficult to maintain, especially when it includes hacks & translations.

**Comment by tjanas** [comment]
GSC is more subjective and less deterministic than organization in the main directories.

**Comment by yo1dog** [comment]
My plan is to download the N8 GSC smdb, convert headers on all ROMs to NES2.0, then create a new smdb.

**Comment by tjanas** [comment]
That should work for most, but not all, as not all translations and hacks will be in the NRS xml.

**Comment by yo1dog** [comment]
Right, but those won't be in the no-intro rom set anyway.

**Comment by yo1dog** [comment]
Another quick question: What source is used for hacked and unreleased ROMs? For example, SNES `Campus Challenge '92 - F-Zero (USA)`

**Comment by tjanas** [comment]
> Another quick question: What source is used for hacked and unreleased ROMs? For example, SNES `Campus Challenge '92 - F-Zero (USA)`.

Probably this: https://snescentral.com/article.php?id=0790

"A while back, bunnyboy came to an agreement with the owner of one of the Campus Challenge carts to [produce a bootleg](https://www.retrousb.com/product_info.php?cPath=29&products_id=91&osCsid=a3b04adaaaefa93d02facc8443af3adb). The bootleg has a hacked version of the game. Most notably, the intro screen was changed to look like the NES Campus Challenge logo. Nevertheless, the hacked version was dumped and may be the only way to play this game. A member of [byuu's forum](https://helmet.kafuka.org/byuubackup2/viewtopic.php@f=21&t=987.html) named hex_user managed to make a restoration hack that attempts to recreate the original logo, using the screenshots of the original version as a reference. I have mirrored the patches [here](https://snescentral.com/0/7/9/0790/campuschallenge_restoration_v02.zip). You can use the tool [Floating IPS](https://www.romhacking.net/utilities/1040/) to patch the files."

Translation patches are generally found at romhacking.net
