### ISSUE TITLE
[SD2SNES] Updated HACKS for Super NES - Pre-Patched Roms included

### ISSUE THREAD

**Issue by adlroux** [frederic-mahe/Hardware-Target-Game-Database#834]
**Updated HACKS for Super NES**

Pre-Patched roms, courtesy of CDRomance.com: 
https://we.tl/t-MsAKKADevA (link available for 7 days)

**Details:**

Final Fight Guy FastROM (Hack)
Version: v1.0
Author: MaxwelOlinda
https://www.romhacking.net/hacks/6356/

Final Fight Guy Unlicensed Hack (Hack)
Version: v0.005
Author: Rotwang
http://www.baddesthacks.net/forums/viewtopic.php?t=654

Final Fantasy V Tweaks (Hack)
Version: v2.5a
Author: T29
https://www.romhacking.net/hacks/6789/

Terminator 2 Arcade Remix (Hack)
Version: v1.0
Author: BillyTime! Games
https://www.romhacking.net/hacks/6490/

SMW Aeron's Golden Cookie Quest (SMW Hack)
Version: v2.3.6
Author: Anorakun
https://www.romhacking.net/hacks/6729/

Zelda ALTTP Redux (Hack)
Zelda ALTTP Redux (Hack) GFX, LR Items
Version: v9.3
Author: ShadowOne333
https://www.romhacking.net/hacks/2594/

Final Fantasy VI - Ted Woolsey Uncensored Edition + Bug Fixes, Updated Opera, & Add-Ons (Hack)
Version: v3.06
Author: RodimusPrimal
https://www.romhacking.net/hacks/1386

**Comment by jadehawk** [comment]
Assuming you got the pre patched roms from the already dead link. Can you provided the CRC/SHA1 checks for the patch roms.. Thanx..

**Comment by adlroux** [comment]
Updated link, available for one week: https://we.tl/t-gprGMP3blS

**Comment by tjanas** [comment]
DO NOT SHARE FILES ROMS HERE.

**Comment by tjanas** [comment]
@adlroux please submit a pull request, with links to the ips/bps PATCHES (e.g. links to pages at romhacking.net).

**Comment by adlroux** [comment]
I did. The original Post I did features link to every Romhacking original pages with the patches
