### ISSUE TITLE
SegaCD: Discrepancies with certain .cues

### ISSUE THREAD

**Issue by bobbertoriley** [frederic-mahe/Hardware-Target-Game-Database#933]
I'm attempting to build/verify the SegaCD pack, and while I've got the majority of the way there, I have ~6 .cue files I haven't been able to match . I was able to hand-fix most of the .cue issues (like the rename issue reported in #646 ), but for the life of me, I cannot figure out the discrepancies with the remaining .cues. The files _look_ right, but have a different hash than what's in the DB.

I've attached the output after running verify_pack which include the SHAs, but here's the list of offending files.
* 2 Japan - A-Z/1 A-L/Keiou Yuugekitai (Japan)/Keiou Yuugekitai (Japan).cue
* 4 Hacks/Lunar - Eternal Blue (US) [Un-Worked Designs v2.0]/LunarEternalBlueUnWorkedV2.cue
* 4 Hacks/Lunar - The Silver Star (US) [Un-Worked Designs]/LunarTheSilverStarUnWorked.cue
* 4 Hacks/Popful Mail (US) [Un-Worked Designs]/PopfulMailUnWorked.cue
* 4 Hacks/Vay (US) [Un-Worked Designs]/VayUnWorked.cue
* 4 Homebrew/Throne (PD)/Throne.cue

Does anyone by chance have the .cue files for these that do match, so I can attempt to discover what the discrepancy is? 

(Sidenote: the Un-Worked Design hacks were all generated using the patch files at http://stargood.org/unworked/index.php; ironically, while the rom contents are good, the .cues included with the patch files weren't. Lunar: Eternal Blue seems to be different than the results in the DB, but that's a different issue. If I can figure out the discrepancy, I can create a PR to update the format for that romhack to match the others.)

[missing.txt](https://github.com/frederic-mahe/Hardware-Target-Game-Database/files/12323642/missing.txt)

**Comment by hotelvictorcharlie** [comment]
Sometimes these issues are caused by differences between dos/unix newlines and requires the files to be converted. Anyway here are the cue files that you're missing.
[cuefiles.zip](https://github.com/frederic-mahe/Hardware-Target-Game-Database/files/12323692/cuefiles.zip)

**Comment by bobbertoriley** [comment]
Figured out the discrepancies, and they mostly appear to be on my end.

* Keiou Yuugekitai (Japan): the .cue from redump.org has "CATALOG 0000000000000" on the first line; removing that generates the same sha as the database.
* Throne (PD): My .cue had the wrong mode for the .iso file (2053 vs 2048); fixing that generates the same sha as the database. 
* The Un-Worked Design Hacks: the audio files in the .cue files provided by http://stargood.org/unworked/index.php are listed as WAVE instead of BINARY. Adjusting them to BINARY for those files generates the same sha as the database.
* Lunar - Eternal: Exception to the other UD hacks. Looks like it's expecting a packed .bin + .cue instead of the .iso + .wav format created by the other patches.
